---
# install_helm_binary/tasks/download_binary_on_Debian.yml

#
# set github_architecture string so we can download the file from Github (i.e. armv7l => armv7 etc.)
#

- name: 'Set variable for armv7 architecture'
  ansible.builtin.set_fact:
    github_architecture: "armv7"
  when: 'ansible_architecture == "armv7l"'

- name: 'Set variable for arm64 architecture'
  ansible.builtin.set_fact:
    github_architecture: "arm64"
  when: 'ansible_architecture == "aarch64"'

- name: 'Set variable for amd64 architecture'
  ansible.builtin.set_fact:
    github_architecture: "amd64"
  when: 'ansible_architecture == "x86_64"'

#
# Make sure tar and unzip are installed
#

- name: 'Install tar and unzip'
  ansible.builtin.package:
    name:
      - 'tar'
      - 'unzip'
    state: 'present'

#
# Get the latest release of helm
#

- name: 'Get helm release information'
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/helm/helm/releases/latest'
    return_content: 'true'
  register: 'json_reponse'
  check_mode: 'false'

- name: 'Extract latest version from release information'
  ansible.builtin.set_fact:
    latest_helm_release: "{{ json_reponse.json.tag_name }}"

- name: 'Download latest helm release'
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-{{ latest_helm_release }}-linux-{{ github_architecture }}.tar.gz"
    dest: "/tmp/helm-{{ latest_helm_release }}-linux-{{ github_architecture }}.tar.gz"
    checksum: "sha256:https://get.helm.sh/helm-{{ latest_helm_release }}-linux-{{ github_architecture }}.tar.gz.sha256sum"
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify:
    - 'Extract helm executable from archive'

- name: 'Flush handlers to extract binary now'
  ansible.builtin.meta: flush_handlers
